# Generated by Django 3.2 on 2023-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_added',
            field=models.BooleanField(default=True),
        ),
    ]
